# Generated by Django 5.0.2 on 2024-02-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhosphoProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniprot_code', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('gene_name', models.CharField(max_length=255)),
                ('protein_name', models.TextField()),
                ('modification_type', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('window_5_aa', models.TextField()),
                ('sequence', models.TextField()),
                ('method', models.CharField(max_length=50)),
                ('reference', models.IntegerField()),
                ('alphafold_link', models.URLField()),
            ],
        ),
    ]
