# Generated by Django 5.0.2 on 2024-03-01 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='alphafold_link',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='url',
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='alphafold_structure',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='pdb_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bacphosapp.profile'),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='uniprot_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phosphoprotein',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
