# Generated by Django 5.0.2 on 2024-03-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0004_remove_phosphoprotein_modification_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='method',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='phosphosite',
            name='sequence',
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='sequence',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='phosphosite',
            name='method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phosphosite',
            name='reference',
            field=models.CharField(default='', max_length=100),
        ),
    ]
