# Generated by Django 5.0.2 on 2024-03-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0005_remove_phosphoprotein_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phosphoprotein',
            name='biological_process',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='cellular_component',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='molecular_function',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='molecular_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='protein_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='protein_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
