# Generated by Django 5.0.2 on 2024-03-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0007_alter_phosphosite_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='phosphosite',
            name='reference',
        ),
        migrations.AddField(
            model_name='phosphosite',
            name='references',
            field=models.ManyToManyField(to='bacphosapp.reference'),
        ),
    ]
