# Generated by Django 5.0.2 on 2024-03-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0011_phosphoprotein_approved_phosphosite_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phosphoprotein',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
