# Generated by Django 5.0.2 on 2024-03-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0012_phosphoprotein_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='alphafold_structure',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='biological_process',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='cellular_component',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='ecocyc_url',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='molecular_function',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='molecular_weight',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='protein_description',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='protein_type',
        ),
        migrations.RemoveField(
            model_name='phosphoprotein',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='modification_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='window_5_aa',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='phosphoprotein',
            name='sequence',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='PhosphoSite',
        ),
    ]
