# Generated by Django 5.0.2 on 2024-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0014_phosphoprotein_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='phosphoprotein',
            name='alphafold_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
