# Generated by Django 5.0.2 on 2024-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0015_phosphoprotein_alphafold_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='phosphoprotein',
            name='coli_strain',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
