# Generated by Django 5.0.2 on 2024-04-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0016_phosphoprotein_coli_strain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phosphoprotein',
            name='pdb_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
