# Generated by Django 5.0.2 on 2024-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacphosapp', '0017_alter_phosphoprotein_pdb_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='phosphoprotein',
            name='function',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='go_bp',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='go_cc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='go_mf',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='phosphoprotein',
            name='protein_f',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
